import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Dati {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.

  @PrimaryKey(autoGenerate: true)
  final int? id;

  final int week;

  final double distance;

  final double steps;

  final double calories;

  final double floors;

  //Default constructor
  Dati(this.id, this.week, this.distance, this.steps, this.calories,
      this.floors);
}

@entity
class Person {
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final String? name;

  final String? surname;

  final int? age;

  final String? avatar;

  final double? weight;

  final double? height;

  final int? avgDailySteps;

  final int? dateOfBirth;

  final int? durationOfSleep;

  //Default constructor
  Person(
    this.id,
    this.name,
    this.surname,
    this.age,
    this.avatar,
    this.weight,
    this.height,
    this.avgDailySteps,
    this.dateOfBirth,
    this.durationOfSleep,
  );
}
