// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKOE2VAC4sIVNihiygUW44z64Saz-3ogY',
    appId: '1:93142974302:web:bfb2642651de61b6dc99cf',
    messagingSenderId: '93142974302',
    projectId: 'kipos-90494',
    authDomain: 'kipos-90494.firebaseapp.com',
    storageBucket: 'kipos-90494.appspot.com',
    measurementId: 'G-4QJJH41T7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8Y7UQhBuMhGtk4jWPU-0vEbPOIfhCfM',
    appId: '1:93142974302:android:bfcf375f1166544edc99cf',
    messagingSenderId: '93142974302',
    projectId: 'kipos-90494',
    storageBucket: 'kipos-90494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyM5ZzXiiy9CwBShf_Js_ViQUNtaE13U',
    appId: '1:93142974302:ios:039c27696bcfb1a7dc99cf',
    messagingSenderId: '93142974302',
    projectId: 'kipos-90494',
    storageBucket: 'kipos-90494.appspot.com',
    iosClientId:
        '93142974302-saboc454qouhf85h3jbo2ltnpshshhl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kipos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyM5ZzXiiy9CwBShf_Js_ViQUNtaE13U',
    appId: '1:93142974302:ios:79ba7a51e4145338dc99cf',
    messagingSenderId: '93142974302',
    projectId: 'kipos-90494',
    storageBucket: 'kipos-90494.appspot.com',
    iosClientId:
        '93142974302-kvpmvbccnp24rkqcb65beohubciuh5lu.apps.googleusercontent.com',
    iosBundleId: 'abc',
  );
}
